version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: hono-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: hono_backend
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - hono-network

  mongo-express:
    image: mongo-express:latest
    container_name: hono-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - hono-network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  hono-network:
    driver: bridge
